version: '3.1'
services:
  slay_ingest_postgres:
    container_name: slay_ingest_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: host all all all
    ports:
      - 54322:5432
  slay_q_server:
    container_name: slay_q_server
    restart: always
    image: "node:20"
    user: 'node'
    working_dir: /home/node/app
    environment:
      - SLAY_Q_DATABASE_URL=postgresql://postgres:postgres@slay_ingest_postgres:5432/postgres
      - SLAY_Q_SECRET=G,4DgB$.?>X]"w}w1745Xq2nKoM4BG74
      - SLAY_Q_CRON_URL=http://host.docker.internal:3000/api/slay-q
    volumes:
      - './slay-config.json:/home/node/app/slay-config.json:ro'
    command: "npx --yes @slay-pics/slay-q-server@latest /home/node/app/slay-config.json"
